---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - geerlingguy.homebrew
    - Shashikant86.ansible-ios-ci
