---
- name: Ensure /etc/ansible directory exists.
  file:
    path: /etc/ansible
    state: directory
  become: yes

- name: Install Ruby Gems required for iOS app developement
  gem: name={{item}} state=latest
  with_items:
   - bundler
   - rake
   - cocoapods
   - fastlane
   - xcov
   - xcpretty
   - xcode-install


- name: Ensure that defaults state disabled.
  shell: "{{ item }}"
  with_items:
    - defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false
    - defaults write NSGlobalDomain NSWindowResizeTime -float 0.001
    - defaults write com.apple.dock expose-animation-duration -int 0
    - defaults write com.apple.dock launchanim -bool fals
  changed_when: false

- name: Enable Developer Tools and Never Sleep Mode
  shell: "{{ item }}"
  with_items:
    - DevToolsSecurity -enable
    - systemsetup -setsleep Never
    - systemsetup -setharddisksleep Never
    - systemsetup -setcomputersleep Never
    - systemsetup -setdisplaysleep Never
  changed_when: false

- name: Ensure that animations are disabled
  shell: "{{ item }}"
  with_items:
    - defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false
    - defaults write NSGlobalDomain NSWindowResizeTime -float 0.001
    - defaults write com.apple.dock expose-animation-duration -int 0
    - defaults write com.apple.dock launchanim -bool false
  changed_when: false

- name: Software Updates
  shell: "{{ item }}"
  with_items:
    - softwareupdate -i -a - ignore iTunes
    - softwareupdate --schedule off
