---
- hosts: all
  connection: local

  vars_files:
    - ../vars/main.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - geerlingguy.homebrew

  tasks:
     - include: ios-ci-playbook.yml
