---
- hosts: localhost
  connection: local
  remote_user: root

  vars_files:
    - ../defaults/main.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - geerlingguy.homebrew

  tasks:
     - include: ansible.yml
     - include: ruby-setup.yml
     - include: xcode-install.yml
     - include: macos-defaults.yml
