---
- name: Run Ansible Tasks
  include: ansible.yml

- name: Run Ruby Tasks
  include: ruby-setup.yml

- name: Run Xcode Tasks
  include: xcode-install.yml

- name: Run macOS Tasks
  include: macos-defaults.yml
